from shared.observability.logging import (
    configure_logging,
    get_logger,
    trace_id_var,
    workflow_id_var,
    run_id_var,
    activity_type_var,
    request_id_var,
    task_queue_var,
)
from shared.observability.metrics import (
    REGISTRY,
    record_llm_call,
    get_metrics_endpoint,
    workflow_started_total,
    workflow_completed_total,
    workflow_failed_total,
    workflow_duration_seconds,
    activity_duration_seconds,
    activity_completed_total,
    activity_failed_total,
    llm_requests_total,
    llm_request_duration_seconds,
    llm_tokens_input_total,
    llm_tokens_output_total,
    llm_cost_dollars,
    documents_processed_total,
    pdf_extraction_duration_seconds,
    human_review_wait_seconds,
    human_review_started_total,
    human_review_approved_total,
    human_review_revised_total,
    human_review_timeout_total,
    active_workflows,
    active_activities,
)
from shared.observability.tracing import setup_tracing, setup_temporal_runtime
from shared.observability.middleware import ObservabilityMiddleware
