global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'contract_review_worker'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9001']
        labels:
          group: 'python-worker-metrics'
  - job_name: 'contract_review_api'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:9002']
        labels:
          group: 'python-api-metrics'
  - job_name: 'otel_collector'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8889']
        labels:
          group: 'otel-metrics'
  - job_name: 'temporalmetrics'
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'host.docker.internal:8000'
          - 'host.docker.internal:8001'
          - 'host.docker.internal:8002'
          - 'host.docker.internal:8003'
          - 'host.docker.internal:8004'
        labels:
          group: 'server-metrics'
      - targets:
          - 'host.docker.internal:8077'
          - 'host.docker.internal:8078'
        labels:
          group: 'sdk-metrics'
      - targets:
          - 'host.docker.internal:9323'
        labels:
          group: 'docker-metrics'
      - targets:
          - 'host.docker.internal:9187'
        labels:
          group: 'postgres-metrics'
